### ISSUE TITLE
Menu de áudio com tamanho incorreto

### ISSUE THREAD

**Issue by devkcud** [SegundoInformatica/faisca-ui#19]
TL;DR: *O tamanho do menu de áudio é o mesmo do título.*

Esta simples modificação possivelmente ja arrumaria _**(NÃO TESTADO)**_:

```css
section.audio-box {
    width: fit-content;
    /* ... */
}

/* ... */
```

![image](https://github.com/SegundoInformatica/faisca-ui/assets/49255580/ad5f5a1d-c189-45e5-a8ee-7fd398926150)
