### ISSUE TITLE
Definir tamanho correto do título

### ISSUE THREAD

**Issue by devkcud** [SegundoInformatica/faisca-ui#20]
TL;DR: _Quando o título é muito longo ele quebra a linha das imagens_

Uma possível solução seria _**(NÃO TESTADO)**_:
```css
div.artigo-header section.textual {
  flex: 1;
}
```

![image](https://github.com/SegundoInformatica/faisca-ui/assets/49255580/47d9ca99-f4d6-4908-b11d-7e9195c647d7)
